name: Release
on:
  push:
    branches: [master]

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: NPM Release
    uses: scttcper/github-actions/.github/workflows/npm-release.yml@main
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
